### ISSUE TITLE
AI implementation

### ISSUE THREAD

**Issue by CristianDum** [cmput396/assignment3#2]
- Tailor MCTS code to work with current methods
- Implement placement function
-      Optional: add second tier of computation for pscore()

**Comment by stuarthoye** [comment]
The code from the webpage is very general pseudocode.  We'll need to adapt it extensively for it to be useful in our application.

**Comment by CristianDum** [comment]
Yup. I had to get more familiar with the methods you already put in place
and use those. The pseudocode was left in to just serve as a guidline.
Could we use/modify the "is_legal_move" to determine if the game is over?
That was the next thing that could be done.

**Comment by stuarthoye** [comment]
The game can end in two ways:
1. When there are no legal moves left to make.
2. When both players pass.

Line 42 in Dvonn_Control is the start of the update_state() function.  That function tests whether both players have passed and whether either player has any valid moves left.  If both players have passed, or if neither player has any valid moves, then the phase is updated to "Gameover".

That function calls Board.moves(), which in turn calls valid_move() to verify that the move is valid.  There isn't any need to write another function to test the game is terminal.  If you need to test whether the game is over, you can test whether State.phase == "Gameover".

Is that sensible?  Is there some particular purpose you have that isn't satisfied by that?

**Comment by CristianDum** [comment]
That would work well. The purpose was to test for leaf nodes in the game
tree.

On Nov 17, 2016 2:44 PM, "Stuart" <notifications@github.com> wrote:

The game can end in two ways:
1. When there are no legal moves left to make.
2. When both players pass.

Line 42 in Dvonn_Control is the start of the update_state() function. That
function tests whether both players have passed and whether either player
has any valid moves left. If both players have passed, or if neither player
has any valid moves, then the phase is updated to "Gameover".

That function calls Board.moves(), which in turn calls valid_move() to
verify that the move is valid. There isn't any need to write another
function to test the game is terminal. If you need to test whether the game
is over, you can test whether State.phase == "Gameover".

Is that sensible? Is there some particular purpose you have that isn't
satisfied by that?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/cmput396/assignment3/issues/2#issuecomment-261379163>,
or mute the thread

**Comment by CristianDum** [comment]
Left to do:
- write simulation policy
- write placement strategy
